### ISSUE TITLE
Diagnostics Documentation

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Documentation#108]
Docs needed for:

- Basic info on how to capture diagnostics
- Documentation for advanced users that might need to create their own tracers.

**Comment by alistairjevans** [comment]
@tillig; did you want to take this one, or shall I do this and you take the dot-graph docs? Didn't know if you might want to put some specific content in about DiagnosticSource.

Actually, might it be worth splitting the docs for this into 'simple diagnostics instructions', i.e. how to attach the default tracer and understand it, and advanced 'how to use the Diagnostic Source'?  Feels like we could maybe put the simple diagnostics more front-and-centre.

**Comment by tillig** [comment]
I can take it. I'll do the whole "quick start/easy tracer" thing up front, then explain the two different tracers we offer, then dig down into custom tracing and DiagnosticSource for the advanced scenarios.

**Comment by tillig** [comment]
Close language in PRs (`Resolves #108`) doesn't seem to be working. 🤔 

Closed via #120.

**Comment by alistairjevans** [comment]
I think the close language only works when merging into the default branch....

**Comment by tillig** [comment]
OOOOOHHHHH yeah I guess that's right. I never picked up on that. Thanks!
