### ISSUE TITLE
Update API docs for v6

### ISSUE THREAD

**Issue by tillig** [autofac/Documentation#125]
We need to run the API documentation generation process and update that documentation with the 6.0.0 APIs after everything is published. It does require the NuGet packages be published so the API doc rendering project can consume them all and generate linked docs.

**Comment by alexmg** [comment]
The Autofac.ServiceFabric 4.0.0 package has now been published.

**Comment by tillig** [comment]
Took a bit but I figured out how to get Sandcastle Help File Builder working with `<PackageReference>` (since there's no `packages` folder and using `dotnet build` doesn't actually copy literally every reference into the build output folder).

API docs for v6 are built and published.
