### ISSUE TITLE
Add Azure Functions integration guide

### ISSUE THREAD

**Issue by srmagura** [autofac/Documentation#150]
## Problem Statement

There's no documentation on using Autofac with Azure Functions.

## Desired Solution

I've figured out how to do it and would like to contribute a guide to help other users. It is less than 20 lines of code.

## Alternatives You've Considered

If you prefer, I can write a post on my personal blog instead. **Please let me know if you would like this in the official documentation or on my blog.**

**Comment by tillig** [comment]
I'd be open to a PR here. Probably a separate page with an entry like the other app types in the integration section. I don't know that I'll be able to try the code samples out myself so I'll just have to trust you. ;)
