### ISSUE TITLE
4.2 Implicit RelationshipTypes - KeyedServiceLookup

### ISSUE THREAD

**Issue by Stroked** [autofac/Documentation#17]
I was reading the documentation on your website and noticed something confusing.

In the sample code for the usage of IIndex<X, B> there seems to be a typo but I just want to make sure I'm not missing the point.

```
 public class A
 {
   IIndex<string, B> _b;

   public A(IIndex<string, B> b) { _b = b; }

   public void M()
   {
     var b = this._b["first"];
     **_b.DoSomething();**
   }
 }
```

The last line, "_b.DoSomething()", shouldn't that be b.DoSomething (without the underscore)

**Comment by tillig** [comment]
Yep, nice catch. Updated the doc and pushed just now; should be live shortly (after the doc build). Thanks!
