### ISSUE TITLE
The layout seems completely broken.

### ISSUE THREAD

**Issue by gliljas** [autofac/Documentation#177]
Some time ago, the site looked like this:
https://web.archive.org/web/20220412193519/https://autofac.readthedocs.io/en/latest/

Rather easy to navigate and visually pleasing.

Now, it's nowhere near that. The theme has changed to "classic", and it's not good. I doubt it was intentional.

**Comment by alistairjevans** [comment]
Looks to be related to https://github.com/readthedocs/readthedocs.org/issues/10670. ReadTheDocs have changed their defaults.

**Comment by gliljas** [comment]
Indeed. Good catch.
