### ISSUE TITLE
ConfigurationSettingsReader is gone

### ISSUE THREAD

**Issue by AkosLukacs** [autofac/Documentation#18]
The  [Configuring the Container](https://github.com/autofac/Documentation/blob/master/docs/configuration/xml.rst#id42) paragraph mentions `ConfigurationSettingsReader` class, but it looks like it's gone in v4.

**Comment by tillig** [comment]
You'll notice there are two major sections - the new way (using Microsoft configuration) and the previous way (which specifically mentions the 3.x series). The 4.0 way is totally different internally so many of the old classes are gone.

**Comment by AkosLukacs** [comment]
Oh, read that actually fine manual. Sorry.
