### ISSUE TITLE
Misleading information for ASP.NET Core

### ISSUE THREAD

**Issue by smarts** [autofac/Documentation#26]
Under [this section](https://github.com/autofac/Documentation/blob/master/docs/integration/aspnetcore.rst#id16)
> No manual controller registration. You used to be required to register all of your controllers with Autofac so DI would work. The ASP.NET Core framework now automatically passes all controllers through service resolution so you don't have to do that.

This information is misleading. It states that you "don't have to" register your controller with Autofac, which IMHO, is different than "you _can't_ register your controller with Autofac". The latter of these 2 behaviors is what I've witnessed.

Scenario:
 - Create a named registration
 - Create a controller registration that instantiates the controller by resolving the named registration as a dependency
 - Put a breakpoint in the controller's constructor and witness that your named registration is not what was injected

**Comment by tillig** [comment]
Are you adding the registration to the container _before_ or _after_ calling `builder.Populate()`?

**Comment by smarts** [comment]
@tillig Before
I also tried using `services.AddMvc().AddControllersAsServices()` (also prior to the controller registration & `builder.Populate()`), but it still doesn't work…

**Comment by tillig** [comment]
Add it after the Populate call.

**Comment by smarts** [comment]
It works. Thanks for the fix/work-around. It feels like this is definitely something that should be documented although admittedly I'm not sure where 😕

**Comment by smarts** [comment]
I'm not sure why the issue is closed. The documentation is still misleading/incomplete
