### ISSUE TITLE
Wrong location for Build instructions

### ISSUE THREAD

**Issue by AndrewSav** [autofac/Documentation#30]
And the bottom of [this file](https://github.com/autofac/Documentation/blob/master/docs/getting-started/index.rst) there is following text:

```
Build instructions are in a README in the root of the code, and more information about the project is in the Contributor Guide
```

This is wrong, there is no instructions in a README  in the root of the code, they are all in  the Contributor Guide.

**Comment by alexmg** [comment]
Thanks pointing out the issue. I have removed the invalid information about the README.
