### ISSUE TITLE
Clarify that AutoActivate() changes registered type

### ISSUE THREAD

**Issue by btzdnl** [autofac/Documentation#37]
It came as a surprise to me that using `.AutoActivate()` means *only* `IStartable` will be registered, unless you also specify `.As<>()`, `.AsSelf()` or whatever.

Combined with `AnyConcreteTypeNotAlreadyRegisteredSource` (like in Prism), this can lead to apparent `.SingleInstance()` violations, if you just slap on `.AutoActivate()`.

I feel the documentation should make it very clear that `.AutoActive()` changes the registered type. The name doesn’t really imply that.

(I may provide a pull request myself later.)

**Comment by tillig** [comment]
Updated. Thanks!
