### ISSUE TITLE
.Net Core and MEF integration

### ISSUE THREAD

**Issue by matthew-a-thomas** [autofac/Documentation#38]
This document needs to be updated with instructions relevant to .Net Core 1.1:
https://github.com/autofac/Documentation/blob/master/docs/integration/mef.rst

Trying to install the "Autofac.Mef" package as recommended yields a package manager error:
 > Package Autofac.Mef 4.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Autofac.Mef 4.0.0 supports: net45 (.NETFramework,Version=v4.5)

**Comment by tillig** [comment]
MEF itself is only a full .NET framework thing. Microsoft.Composition (sometimes called MEF 2) supports .NET Core [but we don't support Microsoft.Composition](https://github.com/autofac/Autofac.Mef/issues/7). I'm not sure clarifying "we support what MEF supports" is super valuable. Were you able to reference System.ComponentModel.Composition from .NET Core somehow?

**Comment by matthew-a-thomas** [comment]
@tillig Thanks for your reply. I had a hunch that was what's going on.

I was a little limited on time yesterday evening so I had to stop short, but my plan was to use the [System.Composition.Convention Nuget package](https://www.nuget.org/packages/System.Composition.Convention/) (which I can reference in .Net Core 1.1) to discover a module (via an interface), then pass Autofac's `ContainerBuilder` into that module through an interface method so that it can register its own stuff. Not sure if there's a better way.

I'll reply back here (hopefully before tomorrow) with relevant details about what works, if you'd like?

**Comment by tillig** [comment]
Oh now that's interesting - tracing things back from the package you mentioned I see a lot of other System.Composition packages that make me wonder if they back-ported classic MEF to .NET Core somehow. I'll add an issue to our MEF repo to look into it, but do let us know what you find. Thanks!

I'll close this issue for now to track the research over there. I'll link back here.
