### ISSUE TITLE
This is a great package, but does this have Chinese document

### ISSUE THREAD

**Issue by lousaibiao** [autofac/Documentation#40]
Does Autofac have Chinese version document? Or are there a group working on translating it that I can join?

**Comment by tillig** [comment]
There isn't any language but English. If you'd like to start translating, you can, but [it doesn't look like ReadTheDocs had great multi language support](https://docs.readthedocs.io/en/latest/i18n.html) - you'd have to figure that out or potentially host a second copy of the docs.

**Comment by lousaibiao** [comment]
@tillig Yeah. I'm doing. I will try to host a copy after I finish.

**Comment by tillig** [comment]
Sounds good. If you get it working let us know and we'll add a link. Thanks!
