### ISSUE TITLE
autofac wcf instance managemenr

### ISSUE THREAD

**Issue by ajaychoudhary01** [autofac/Documentation#41]
Hi,

This is not an issue. I want to understand how autofac handles instance management. I have a WCF service which is registered with its interface (Service contract).
Like.
container.RegisterType<Service>().As<IService>();
How it will manage instance? Will it create instance per call or per session or singleton.?
How it will manage concurrency? Will it be Single or multiple ? 

What is default behaviour of autofac wcf package for this type of registration?

Thanks,
Ajay

**Comment by tillig** [comment]
Please check out [the documentation on WCF integration](http://autofac.readthedocs.io/en/latest/integration/wcf.html). It talks about different lifetimes and includes the following:

> The way Autofac hooks into WCF, it uses an instance provider to resolve your service and dependencies. The instance provider makes use of the service instance context to track the lifetime scope in which your service and its dependencies live.
> 
> What that boils down to: A lifetime scope is created based on the instance context mode of your service.
> 
> If you leave it default, that’s “per session.” One instance of your service will be created when a client calls it, and subsequent calls from that client will get the same instance.

There are links to things with more detail if you look in the docs.
