### ISSUE TITLE
Copyright footer autodated

### ISSUE THREAD

**Issue by jschmid** [autofac/Documentation#44]
The documentation footer states "Copyright 2014". Maybe you want to [update it](https://github.com/autofac/Documentation/blob/36b3d2d118c068ef6c6a81afb9e3490a3c0f1fa3/docs/conf.py#L47) ?

**Comment by tillig** [comment]
From [this article on copyright law](http://www.copyrightlaws.com/copyright-notice-year/):

> The general rule is that the year to include in a copyright notice is the year of first publication of the work.

Basically, you're not supposed to update it.
