### ISSUE TITLE
Can code snippets have syntax highlighting enabled?

### ISSUE THREAD

**Issue by andrewpong** [autofac/Documentation#54]
I'm not sure if this is a bug with the Autofac docs, Read the Docs, Sphinx, pygments, etc., or config setting, but it'd be nice if the C# code samples had syntax highlighting enabled. 

It's all showing up as black in Chrome and Edge for me: [screenshot](https://i.imgur.com/ulSCdYI.png).

 I know Sphinx's [markup docs](http://www.sphinx-doc.org/en/stable/markup/code.html) states that `sourcecode` is an alias for the `code-block` directive, but perhaps switching from `.. sourcecode:: csharp` to `.. code-block:: csharp` might bring syntax highlighting back?

**Comment by tillig** [comment]
Happy to make changes if you know what changes to make. Seems like it was working at one time and then it wasn't. I don't have time right now to research it, so... unless you know the fix, it'll have to wait for a while.

**Comment by andrewpong** [comment]
I'll see what I can do - it's been a while since I've  worked with Python and reStructuredText. I just ran a local build and found some inconsistencies:

1. My local html build has syntax highlighting for [getting-started](https://github.com/autofac/Documentation/blob/3d5fbcdde8a7b272cbc6dd3f469640153d9fe364/docs/getting-started/index.rst), but not for [integration/aspnetcore](https://github.com/autofac/Documentation/blob/3d5fbcdde8a7b272cbc6dd3f469640153d9fe364/docs/integration/aspnetcore.rst).
2. In contrast, the version deployed to Read the Docs doesn't have syntax highlighting on [either](http://autofaccn.readthedocs.io/en/v4.0.0/getting-started/index.html) [page](http://autofaccn.readthedocs.io/en/v4.0.0/integration/aspnetcore.html).

I'll dig into this as I can. At first glance the markup looks fine... maybe it's something with Sphinx's config and/or some side effect elsewhere.

**Comment by tillig** [comment]
IIRC there's a warning when building the aspnetcore page about difficulties parsing the code. I think it had to do with the `$"string{interpolation}"` on the page.

**Comment by andrewpong** [comment]
Yeah, just realized that it's probably some new syntax causing the csharp parser issues when trying to process some of the newer examples.

I changed the `.. sourcecode:: csharp` directives to `.. code-block:: csharp` for integration/aspnetcore and got the following error when trying to run a build using make.bat:

```
D:\Projects\autofac\Documentation\docs\integration\aspnetcore.rst:26:
        WARNING: Could not lex literal_block as "csharp". Highlighting skipped.
D:\Projects\autofac\Documentation\docs\integration\aspnetcore.rst:110:
        WARNING: Could not lex literal_block as "csharp". Highlighting skipped.
```

**Comment by andrewpong** [comment]
I discovered the pygmentize command!

Calling `cat aspnetcore-codeblock1.rst | pygmentize.exe -l csharp -F raiseonerror -v` returns the error below and you're right: it has an error at ` .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)`

```C#
public class Program
    {
      public static void Main(string[] args)
      {
        // The ConfigureServices call here allows for
        // ConfigureContainer to be supported in Startup with
        // a strongly-typed ContainerBuilder.
        var host = new WebHostBuilder()
            .UseKestrel()
            .ConfigureServices(services => services.AddAutofac())
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseIISIntegration()
            .UseStartup<Startup>()
            .Build();

        host.Run();
      }
    }

    public class Startup
    {
      public Startup(IHostingEnvironment env)
      {
        var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile(
```

```
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "~\AppData\Local\Continuum\miniconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "~\AppData\Local\Continuum\miniconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~\.virtualenvs\Documentation-NDACenMM\Scripts\pygmentize.exe\__main__.py", line 9, in <module>
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\cmdline.py", line 543, in main
    return main_inner(popts, args, usage)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\cmdline.py", line 507, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\__init__.py", line 85, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\__init__.py", line 67, in format
    formatter.format(tokens, outfile)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\formatters\terminal.py", line 101, in format
    return Formatter.format(self, tokensource, outfile)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\formatters\terminal.py", line 121, in format_unencoded
    for ttype, value in tokensource:
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\filter.py", line 20, in _apply
    for token in filter_.filter(lexer, stream):
  File "~\.virtualenvs\documentation-ndacenmm\lib\site-packages\pygments\filters\__init__.py", line 196, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: $
```

**Comment by tillig** [comment]
You're gonna love this: I pushed a new FAQ which caused the docs to rebuild and...

**There's syntax highlighting again.**

Well, everywhere except the ASP.NET Core page where there's string interpolation anyway. Which is to be expected.

I am guessing this whole thing is just a bug in how ReadTheDocs last built the docs. I'm gonna close it since... it appears to have resolved itself.

Thanks for the effort in starting to troubleshoot it, though!
