### ISSUE TITLE
Autofac Not Intercepting

### ISSUE THREAD

**Issue by CShelton11** [autofac/Documentation#56]
I cannot get autofac to intercept.  I have the following setup in my .net core application:

// ************************************************
// Logger created:
// ************************************************
```
public class Logger : IInterceptor
{
    public void Intercept(IInvocation invocation)
    {
        // Logging removed for now
        var watch = System.Diagnostics.Stopwatch.StartNew();  // Added break point here
        invocation.Proceed(); 
        watch.Stop();
        var executionTime = watch.ElapsedMilliseconds;
    }
}
```

// ************************************************
// Class Created:
// ************************************************
```
[Intercept(typeof(Logger))]
public class ServiceProxy: ServiceInterface
{
    public User GetUser(String username, String password)
    {
        var service = ServiceHelper.GetODataClaimService();
        var query = from a in service.Users
                            select a;
        var dsq = query.ToDataServiceQuery<User>();
        var result = dsq.ToListSync<User>();
        var user = result.FirstOrDefault();
        return user;
    }
}
```

// ************************************************
// Interface Created:
// ************************************************
```
public interface ServiceInterface
{
    User GetUser(String username, String password);
}
```

// ************************************************
// Interception Configuration
// ************************************************
```
public class Interceptor
{
    public static void Configure()
    {
        var builder = new ContainerBuilder();
        builder.Register(a => new Logger());
        builder.RegisterType<ServiceProxy>().As<ServiceInterface>().EnableInterfaceInterceptors().InterceptedBy(typeof(Logger));  // Tried removing intercepted by
        var container = builder.Build();
        var worker = container.Resolve<ServiceInterface>();
        builder.Build()
    }
}
```

I put a break point in the logger to see if it ever enters that block of code.
It never does.  What am I missing here?
I've tried quite a few configurations but nothing seems to work.
Also - The Configure method is invoked from application Startup..

Please advise.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Extras.DynamicProxy#28
