### ISSUE TITLE
How to register with ASP.NET Core when not using UseStartup()?

### ISSUE THREAD

**Issue by sandersaares** [autofac/Documentation#62]
The ASP.NET Core integration at https://github.com/autofac/Documentation/blob/v4.0.0/docs/integration/aspnetcore.rst assumes that the Startup class is used (via `.UseStartup<T>`). However, this is not necessarily the case - ASP.NET Core can be used without the Startup class.

How is one meant to hook up Autofac in such a situation? The regular `IWebHostBuilder.ConfigureServices()` method does not have an overload that can return `AutofacServiceProvider`.

**Comment by reyou** [comment]
You need to use ConfigureServices() in order to register your services right? 
Without UseStartup<> how do you plan to register your services?

**Comment by sandersaares** [comment]
Yes, I am using `.ConfigureServices()`. But the delegate passed to `IWebHostBuilder.ConfigureServices()` does not have a return type of `IServiceProvider`, so I cannot just use the same code as in the documentation.

**Comment by tillig** [comment]
Sorry for the delay, this is why we try to get folks with questions to ask on StackOverflow and tag it `autofac`. Not so many folks are in the issues list to answer questions, but there are tons of people on StackOverflow that can help when the actual Autofac maintainers can't. And, of course, we _also_ monitor over there.

[I've posted an example showing ASP.NET Core without a `Startup` class.](https://github.com/autofac/Examples/blob/master/src/AspNetCore3NoStartupExample/Program.cs) Hopefully that answers the question.
