### ISSUE TITLE
Populate method missing with latest version

### ISSUE THREAD

**Issue by vRITHNER** [autofac/Documentation#66]
Hello,
I just installed the Autofac package in my dotnet standard class library 2.2;
the following statement doesn't work anymore

` builder.Populate(services);`

Populate method looks like is missing 
When I decompile the assembly, I can't find the method anymore:

![2019-02-04_16h22_07](https://user-images.githubusercontent.com/238842/52217630-22c5b380-2899-11e9-9dee-0ffdd7b34162.png)

Did you change the interface ?
Txs in advance
-v

**Comment by alexmg** [comment]
That method is defined in a separate package.

https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection/

It should be available after installing the package above.

**Comment by vRITHNER** [comment]
Txs for the tips
