### ISSUE TITLE
Documentation of Implicit Relationships isn't quite clear

### ISSUE THREAD

**Issue by Brondahl** [autofac/Documentation#67]
I was recently trying to work out how Func<T> and Func<X,Y,T> bindings should be used, and the documentation of how it should be used at the point of declaring and using the dependency is great! But I think there are 2 steps of the documentation missing:

1) Examples of How you declare and register your dependency (in particular the fact that it's keying off the constructor params and registration is not any different; you don't need to register a lamda, for example)

2) Notes on how Func<??, T> dependencies work when the dependency has other, NON parameterised dependencies (i.e. the fact that Autofac *will* fill them in for us.) 

I'm happy (nay, keen) to try to write those changes to the docs, but want to check that they'd be welcome before doing so.

LMK if you're happy to receive a PR for updates.

**Comment by tillig** [comment]
We totally welcome doc PRs, thanks!
