### ISSUE TITLE
Outdated documentation for asp.net core 2.2

### ISSUE THREAD

**Issue by pantonis** [autofac/Documentation#73]
When using asp.net core 2.2 ```without ConfigureContainer``` documentation is wrong.

Particularly there is not return type in ```ConfigureServices``` method since the method signature in different from the one in the documentation

```
public void ConfigureServices(IServiceCollection services)
{
}
```

where as in documentation of autofac 
```

 // ConfigureServices is where you register dependencies. This gets
  // called by the runtime before the Configure method, below.
  public IServiceProvider ConfigureServices(IServiceCollection services)
  {
    // Add services to the collection.
    services.AddMvc();

    // Create the container builder.
    var builder = new ContainerBuilder();

    // Register dependencies, populate the services from
    // the collection, and build the container.
    //
    // Note that Populate is basically a foreach to add things
    // into Autofac that are in the collection. If you register
    // things in Autofac BEFORE Populate then the stuff in the
    // ServiceCollection can override those things; if you register
    // AFTER Populate those registrations can override things
    // in the ServiceCollection. Mix and match as needed.
    builder.Populate(services);
    builder.RegisterType<MyType>().As<IMyType>();
    this.ApplicationContainer = builder.Build();

    // Create the IServiceProvider based on the container.
    return new AutofacServiceProvider(this.ApplicationContainer);
  }
```

**Comment by tillig** [comment]
You have to change the signature yourself. The default template doesn't include it that way but that's how it works. [See the ASP.NET Core docs on replacing the default service provider.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#default-service-container-replacement)

**Comment by tillig** [comment]
It appears you [double-posted this to StackOverflow](https://stackoverflow.com/questions/56007066/using-autofac-in-asp-net-core-2-2). Please don't double-post. The project owners monitor both places and duplicate questions mean duplicate work and wasted time.

**Comment by pantonis** [comment]
sorry
