### ISSUE TITLE
log4net example only works with Constructor Injection

### ISSUE THREAD

**Issue by jzabroski** [autofac/Documentation#76]
https://github.com/autofac/Documentation/blob/master/docs/examples/log4net.rst

This code doesn't work if you have a component that uses a Service Locator design pattern (`Resolve<T>`), like the following PowerShell cmdlet (PowerShell does not allow calling non-default constructors, and currently does not support `Microsoft.Extensions.DependencyInjection`):

```c#
public class SuperPingCommand : Cmdlet
{
  private ILog _log;
  SuperPingCommand()
  {
     // OnComponentPreparing will have e.Parameters.Count == 0 at time of method entry.
     // The example code leads to no customization of the ILog object constructor.
     // Because of this, there is no nice IoC way to configure semantic logging in PowerShell
    _log = Resolve<ILog>();
  }
}
```

**Comment by tillig** [comment]
Correct. It's an IoC container so our examples show how to inject things. If it's service location, there's no way we know from where you're executing that service location without literally looking at the call stack and walking backwards to find the place from which you ran the `Resolve<ILog>()`... which is well outside the responsibility of an IoC container.

You can use property injection or constructor injection with the example. (And it _is_ just an example - something you can take and build on, not "supported code we distribute.") If you want to support service location... you'll have to write that yourself. Sorry!

**Comment by jzabroski** [comment]
I think I figured out a valid workaround: use indirection to force `Resolve<T>` to invert control by giving ILog a concrete implementation with an extra constructor.

```c#
public class Log<T> : ILog
{
    private ILog _log;
    // this will "trick" AutoFac Resolve to give us an ILogManager
    public Log(ILogManager logManager)
    {
        _log = logManager.GetLogger(typeof(T));
    }
    // Implement ILog interface by forwarding interface calls to _log implementation
}
```

**Comment by tillig** [comment]
What's interesting about the example module is that you don't have to know the `T` when resolving, just get an `ILog` attached to the right type.

If you know the `T` then you don't even need the wrapper. You could do it all with lambdas.

```c#
// Hook log manager into DI.
builder.RegisterInstance(LogManager).As<ILogManager>();

// Register a lambda factory that can take a parameter
// that's a System.Type and create the logger.
builder.Register((ctx, p) => {
  // Get the log manager
  var manager = ctx.Resolve<ILogManager>();
  var type = p.OfType<TypedParameter>().Cast<Type>().FirstOrDefault();
  if(type == null)
  {
    // You didn't pass a parameter, do something default.
    type = typeof(MyDefaultType);
  }
  return manager.GetLogger(type);
}).As<ILog>();
```

Then you can resolve a default logger...

```c#
var log = container.Resolve<ILog>();
```

or you can get a typed logger.

```c#
var log = container.Resolve<ILog>(new TypedParameter(typeof(Type), typeof(SuperPingCommand)));
```

You could [use a delegate factory](https://autofaccn.readthedocs.io/en/latest/advanced/delegate-factories.html) to handle it, or even implement [a registration source](https://autofaccn.readthedocs.io/en/latest/advanced/registration-sources.html).

There are a bunch of ways you can work around it, but there's a sort of meta-point to the log4net module: It's an _example_ to illustrate some of the advanced concepts available to folks. It's not intended to be a copy/paste solution.

If someone wants to take that example, build on it, and support it, I say go for it. It might need some better error handling; maybe it could support the service location idea; and it probably needs to be generic enough that it can be used not just with log4net but with other frameworks. If that was the case, you could even use it for things that aren't logging related (which is also something folks have mentioned in the past). It likely won't be part of core Autofac and there are no current plans to expand the list of extensions, so it'd be up to someone in the community to create and support it.

**Comment by jzabroski** [comment]
@tillig  Hi Travis,

First off, I love these kinds of discussions, because while they start off innocuous, I feel as though, as engineers, we all pursue simplicity, and I can see we are both interested in pursuing simplicity.

In general, you can thing of `container.Resolve<ILog>();` as a nullary function.  If we were to abstract out the default constructor and make it a unary function, then the "base function" would be called `ctor`.  e.g.:

```
 .----- function name                      .----- 1sth parameter pushed onto the stack
 |                                         |
\|/                                       \|/
ctor Request(typeof(ILog))        Request(typeof(ILogManager))
          /|\                                                     
           |
           '------- 0th parameter pushed onto the stack
```

Then Request(ILog) becomes a parameter to itself, and service location is just a specific scenario in IoC where the _type system_ directs the Request/Resolve as opposed to the Lambda Factory.
