### ISSUE TITLE
What is the "Without ConfigureContainer" mechanism?

### ISSUE THREAD

**Issue by jimmcslim** [autofac/Documentation#85]
The page https://github.com/autofac/Documentation/blob/master/docs/integration/aspnetcore.rst has a comment in a code example:

````
  // If you need a reference to the container, you need to use the
  // "Without ConfigureContainer" mechanism shown later.
````

However it is not clear if this is actually shown?

Also, is it possible to combine `ConfigureContainer` and `AddControllersAsServices()`... an example for that would be helpful as well.

**Comment by alsami** [comment]
Ups, something got lost there. Which version of ASP.NET-Core are you on?

Anyway, when **below** ASP.NET Core 3. You can do the following in your `Startup.cs`.

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services)
{
   // add stuff to services, like services.AddMvc();
   var containerBuilder = new ContainerBuilder();
   // add stuff to the containerBuilder
   containerBuilder.Populate(services);
   var container = container.Build();
   return new AutofacServiceProvider(container);
}
```

I will create a PR soon to fix that. 



> Also, is it possible to combine `ConfigureContainer` and `AddControllersAsServices()`... an example for that would be helpful as well.

What do you mean by that? Would you eloberate?

**Comment by jimmcslim** [comment]
Actually I don't think I had a further problem, or whatever it was, I've forgotten it! Thanks!

**Comment by alsami** [comment]
Okay, then your question should be answered now. We have added a sample again on how to do it with ASPNET Core version < 3.0 and without configure container.
