### ISSUE TITLE
It would be nice to have an example of the uniqueness of Instance Per Lifetime Scope in nested scope

### ISSUE THREAD

**Issue by yepeekai** [autofac/Documentation#88]
In addition to the 2 samples provided, I think it would be nice/important to have one about the bolded sentence 

> A component with per-lifetime scope will have at most a single instance per nested lifetime scope

```
using(var scope3 = container.BeginLifetimeScope())
{
    var w3 = scope3.Resolve<Worker>();
    using(var scope4 = scope3.BeginLifetimeScope())
    {
        var w4 = scope4.Resolve<Worker>(); //w3 and w4 are 2 different instances
    }
}
```

I know the sentence sounds ok but I was in the impression that child scope were using parent scope instances and having an example would have cleared things out.

**Comment by alistairjevans** [comment]
Sounds sensible to me, do you want to raise a PR for the additional example in [instance-scope.rst](https://github.com/autofac/Documentation/blob/master/docs/lifetime/instance-scope.rst)?

**Comment by yepeekai** [comment]
I will look into it, but gotta have to wait since my schedule is full at the moment. Thanks
