### ISSUE TITLE
AutofacChildLifetimeScopeServiceProviderFactory setup documentation is invalid.

### ISSUE THREAD

**Issue by Coderrob** [autofac/Documentation#90]
Incorrect documentation page:
https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#using-a-child-scope-as-a-root

The documentation explicitly showing how to setup the `AutofacChildLifetimeScopeServiceProviderFactory` where it takes 0 constructor arguments is incorrect. 

```
    var host = Host.CreateDefaultBuilder(args)
        .UseServiceProviderFactory(new AutofacChildLifetimeScopeServiceProviderFactory())
        .ConfigureWebHostDefaults(webHostBuilder => {
```

As of `Autofac.Extensions.DependencyInjection, Version=5.0.1.0` the `AutofacChildLifetimeScopeServiceProviderFactory` does not have any empty constructor.

https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/master/src/Autofac.Extensions.DependencyInjection/AutofacChildLifetimeScopeServiceProviderFactory.cs

**Comment by alsami** [comment]
Thanks for the heads up I'll adjust the documentation soon.

**Comment by ansaridawood** [comment]
.NET Core 3.0 Doc looks deprecated
https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting

I followed the steps and the first area I got stuck it at 
`      builder.RegisterModule(new AutofacModule());`

There is no `AutofacModule` class, is it my responsibility to create this class by inheriting IModule?
I have added `Autofac.Extensions.DependencyInjection` 5.0.1

Am I missing any step?

A quick code for Autofac integration in .NET Core 3.0 would be appreciated, as I am stuck on this. Probably many others are too.
Thanks in advance.

**Comment by tillig** [comment]
ASP.NET Core 3.0 integration is a separate topic from this, but [the docs on it are already there](https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting). If that's not enough, please file a separate issue instead of adding to this one.

**Comment by ansaridawood** [comment]
> ASP.NET Core 3.0 integration is a separate topic from this, but [the docs on it are already there](https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting). If that's not enough, please file a separate issue instead of adding to this one.

I have updated my comment, let me know if I am missing something

**Comment by tillig** [comment]
**Please create a new issue if you have questions that are not related to `AutofacChildLifetimeScopeServiceProviderFactory` documentation**, which is what this issue is about. I'll remove any additional comments on this extra topic in an effort to keep this one on track. Thanks!

**Comment by Coderrob** [comment]
> .NET Core 3.0 Doc looks deprecated
> https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting
> 
> I followed the steps and the first area I got stuck it at
> ` builder.RegisterModule(new AutofacModule());`
> 
> There is no `AutofacModule` class, is it my responsibility to create this class by inheriting IModule?
> I have added `Autofac.Extensions.DependencyInjection` 5.0.1
> 
> Am I missing any step?
> 
> A quick code for Autofac integration in .NET Core 3.0 would be appreciated, as I am stuck on this. Probably many others are too.
> Thanks in advance.

As an aside @ansaridawood I think you're taking the `AutofacModule` too literally. I believe the documentation was meant to represent registering your own custom modules there. https://autofaccn.readthedocs.io/en/latest/configuration/modules.html
