### ISSUE TITLE
.NET Core 3.0 Docs needs update

### ISSUE THREAD

**Issue by ansaridawood** [autofac/Documentation#91]
.NET Core 3.0 Doc looks deprecated
https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting

I followed the steps and the first area I got stuck it at
`builder.RegisterModule(new AutofacModule());`

There is no AutofacModule class, is it my responsibility to create this class by inheriting IModule?
I have added `Autofac.Extensions.DependencyInjection` 5.0.1

Am I missing any step?

A quick code for Autofac integration in .NET Core 3.0 would be appreciated, as I am stuck on this. Probably many others are too.
Thanks in advance.

**Comment by tillig** [comment]
It appears there's some confusion around what's being shown here.

That `AutofacModule` is simply an example of something from your own app you could register. I've pushed an update to the docs to hopefully make that more clear.

```c#
      // ConfigureContainer is where you can register things directly
      // with Autofac. This runs after ConfigureServices so the things
      // here will override registrations made in ConfigureServices.
      // Don't build the container; that gets done for you by the factory.
      public void ConfigureContainer(ContainerBuilder builder)
      {
        // Register your own things directly with Autofac, like:
        builder.RegisterModule(new MyApplicationModule());
      }
```

You might also be interested in the Autofac Examples repo [where we have a live, working example of ASP.NET Core 3 integration](https://github.com/autofac/Examples/tree/master/src/AspNetCore3Example).

It's hard to provide enough detail and documentation to show where things go but also make quick starts actually quick and short enough that people read them. I think with the new update along with the example repo you should be on your way.
